### ISSUE TITLE
EoL TraitBank: error 404 on all species. 

### ISSUE THREAD

**Issue by rvosa** [ropensci/traits#112]
Maybe to do with the new beta that they are launching?

**Comment by sckott** [comment]
i'd think so as well. their APIs AFAICT suddenly changed, I didn't get any warning 😢

**Comment by sckott** [comment]
i can only see traits accessible via their new "cypher" service https://github.com/EOL/eol_website/blob/master/doc/query-examples.md

i asked about it here https://discuss.eol.org/t/where-does-traitbank-live-wrt-api-access/816

**Comment by sckott** [comment]
@rvosa sounds like it's only available via their cypher service now. here's an example, note to self

```r
library(crul)
x = crul::HttpClient$new(
    url = "https://eol.org", 
    headers = list(Authorization = Sys.getenv("EOL_CYPHER_KEY"))
)
res = x$get("service/cypher", query = list(query = "MATCH (n:Trait) RETURN n LIMIT 1;"))
jsonlite::fromJSON(res$parse("UTF-8"), FALSE)
```

not an example for traits yet ...
