### ISSUE TITLE
EOL traitbank query

### ISSUE THREAD

**Issue by BenMerSci** [ropensci/traits#117]
Is there a way to get trait information from EOL with the function traitbank (or any other function?) without using Cypher queries? Or is it the only way since the traits are stored in graphs based on neo4j?

**Comment by sckott** [comment]
Its the only way AFAIK, and looks like you can't use the webpage anymore. Do you need help with a cypher query?

**Comment by BenMerSci** [comment]
Just to make sure in the first place, is the authentication key needed to query the traitbank database the same as the one present in the url of my account page of the EOL website?
 exemple: https://eol.org/users/"authentication_key"

**Comment by sckott** [comment]
i don't know. I don't think so though

**Comment by BenMerSci** [comment]
It was indeed an authentication key problem! Also sorry for the bother, got some issue tracking who worked on which package/function therefore who to contact. Thank you @sckott !
