### ISSUE TITLE
Bird Life International data

### ISSUE THREAD

**Issue by sckott** [ropensci/traits#12]
from convo in ropensci/taxize#344 from @davharris 

Code in his branch at https://github.com/davharris/traits/commit/cfa8c8200b6397c0868b8f7c4b29dd9c5d362768

**Comment by davharris** [comment]
Two tables down, but there are a few more still worth grabbing.

Any idea what's going on in the first table on [this page](http://www.birdlife.org/datazone/species/factsheet/22721692/additional) (red list criteria)? Is the species "Critically Endangered" AND "Endangered" AND "Vulnerable	"? Any idea what the second column is talking about (e.g. "B2ab(i,ii,iii,v)")?

Thanks!

**Comment by sckott** [comment]
TBH I haven't looked at IUCN stuff much at all.  And Ed is the one that wrote the iucn fxns in this pkg. 

on this page http://www.iucnredlist.org/static/categories_criteria_3_1 go to the section `Annex 2: Citation of the IUCN Red List Categories and Criteria`

Seems that e.g., `B2ab(i,ii,iii,v)` is another way of saying `EN` as well as that i, ii, iii, v subsections apply within `B2ab`

**Comment by davharris** [comment]
Okay, thanks.  I’ll follow up on the criteria when I have some more time.  Appreciate the pointer!

**Comment by sckott** [comment]
closing
