### ISSUE TITLE
change maintainer on cran

### ISSUE THREAD

**Issue by sckott** [ropensci/traits#128]
@dlebauer when you get a chance, could you submit a new version to cran changing the maintainer to you? not urgent, but any correspondence from cran will go to me right now, so it'd be good to have it go to you instead. thanks!

**Comment by dlebauer** [comment]
@sckott I am working on this in #130 but am working through some bugs (Perhaps we can close this issue as duplicate?)

Currently stuck on https://github.com/ropensci/traits/issues/131

**Comment by dlebauer** [comment]
version 0.5.1 has been released with new maintainer
