### ISSUE TITLE
possible data source: trophic interactions

### ISSUE THREAD

**Issue by kgturner** [ropensci/traits#15]
https://zenodo.org/record/13751?ln=en#.VLNE-XudtZ8

Currently embargoed, but authors intend to make it open.

**Comment by sckott** [comment]
Thanks! We'll have a look

**Comment by sckott** [comment]
hmm, actually gonna close cause trophic interactions I don't think fit here that well, better in e.g., https://github.com/PoisotLab/rInteract

**Comment by sckott** [comment]
but thanks for bringing it to attn here @kgturner
