### ISSUE TITLE
EML for trait data

### ISSUE THREAD

**Issue by sckott** [ropensci/traits#16]
hey @cboettig 

@dlebauer and I were talking about EML - We're curious - Do you think EML could be used in this package as a way to output a common format across the various sources of trait data?  That is, various sources used in this package return different things (e.g., a list of metadata and data, or just a dataframe), but would be cool to serialize to a common format like EML - which would have added benefit of then being able to share easily to KNB, etc.

**Comment by cboettig** [comment]
Yup, I think this should work.  (not sure how I missed this thread originally)

**Comment by sckott** [comment]
cool cool, will try that soon
