### ISSUE TITLE
Merge BETYdb table queries into a single generic function

### ISSUE THREAD

**Issue by dlebauer** [ropensci/traits#26]
## Create a single function to query tables in BETYdb.

waiting / depends on #77
## Features to implement:
- [ ] Replace `betydb_<tablename>` functions with one function that takes tablename as an argument
  - call should be something like `betydb_query(table = 'citations', key = '', baseurl = 'https://www.betydb.org', apiversion = 'beta', ...)`
  - default key, baseurl, apiversion as above
  - (@sckott is there a preferred naming?)
  - `...` will accept one or more arguments of the form `<field> = 'searchstring'` where `field` is a valid API endpoint / field in the table
  -  function parameter can be any valid endpoint for the table ( ([docs](https://www.betydb.org/api/docs)) )
## Tests
- [ ] write tests. These do not need to be comprehensive, just make sure that the fields exist and have the correct type

The following queries should work: 

``` r
betydb_query(table = 'citation', id = 1)`
betydb_query(table = 'species', genus = 'Salix')`
betydb_query(table = 'variables', name = 'Vcmax', baseurl = 'https://www.betydb.org')`
betydb_query(table = 'citation', author = 'Aasamaa')` # returns 2
betydb_query(table = 'citation', author = 'Aasamaa', year = 2010)` # returns 1
```
## References
- API description with examples: https://pecan.gitbooks.io/betydb-data-access/content/API/beta_API.html
- API Endpoint definitions: https://www.betydb.org/api/docs 
- The url that needs to be constructed is like https://www.betydb.org/api/beta/citations?id=1&key=
  The BETYdb table queries `betydb_traits`, `betydb_yields`, `betydb_citations`, etc were removed (PR #27) 
- these functions were last seen / can be found in ede82fcdec11cd8d012cccefa201c2c73a1174aa. 
## feedback

@sckott @gsrhode @robkooper @max-zilla.
- does this sound like a sensible approach? vs. original implementation of separate functions for each table
- any other suggestions?
- I propose all table joins be done within R; this should make it easier for me to develop without having to fiddle with constructing urls. I don't think our current api supports joins (?)

**Comment by sckott** [comment]
@dlebauer okay, thanks

**Comment by sckott** [comment]
@dlebauer should I close this ?  Looks like your #27 PR address this, right?

**Comment by dlebauer** [comment]
@sckott no, I made this issue at the same time as #27 as a place-holder for re-implementing the broken functions that I removed in that pull request.

The test file in PR #29 has the following function that doesn't work, which is where I got stuck trying to put the URL together ... I'd appreciate help on that ... (here is the [API documentation](https://www.authorea.com/users/5574/articles/7062/_show_article#sec__colon__betyapi))

```r
debugonce(betydb_http)
betydb_traits(genus = "Miscanthus", author = "Arundale", trait = "yield")
```

**Comment by sckott** [comment]
@dlebauer can this be closed, been a while, not sure about the details

**Comment by dlebauer** [comment]
Close
