### ISSUE TITLE
BETYdb API

### ISSUE THREAD

**Issue by dlebauer** [ropensci/traits#3]
Our API is implemented, but has not been widely used, so it would benefit from feedback and pull requests.
 
* repo: https://github.com/PecanProject/bety/
* documentation by example:  https://authorea.com/users/5574/articles/7062/
* PEcAn interface to BETYdb (uses DBI interface: https://github.com/PecanProject/pecan/tree/master/db/R)

Most of the tables will return results with many uninformative foreign key integers. But the traits object will return more useful information, e.g. https://betydb.org/traits/219.xml 

Our lead Ruby on Rails / database developer is @gsrohde, while @robkooper, @mdietze, and I work on PEcAn, a suite of R packages that use BETYdb for ecosystem modeling. We will try to keep up with your requests and help in any way we can because it will be very valuable to us to have this working well at all, and to provide access via your tools in particular.

**Comment by dlebauer** [comment]
@sckott let's chat so we can define the functions' input and output

**Comment by sckott** [comment]
sounds good

**Comment by sckott** [comment]
@dlebauer got first fxn for bety - see the readme - any feedback?

Also, Are there more docs for the API besides https://www.authorea.com/users/5574/articles/7062 ?  There are some parameters you use in the examples, but there isn't a clear list of definitions of each parameter, and which parameters are allowed with each endpoint (/traits, /species, etc.)

**Comment by sckott** [comment]
@dlebauer okay, updated with more fxns - see readme https://github.com/ropensci/traits#betydb 

Does it make sense to have two functions for each endpoint? e.g. for `/citations` have `bety_citations()` and `bety_citation()` where the latter requires an ID and other parameters and will give back a list with variable output given input params - while the former always gives back a data.frame

**Comment by dlebauer** [comment]
Thanks! This is a good place to start. My next step will be to test these out to see what they are doing, and have asked @phenolphtalein to explain your questions and update the documentation in PecanProject/bety#207.

My initial impression is that we should not expose any uses of keys in the arguments of exported functions, in order to prevent humans from having to reference records by arbitrary integers (as opposed to fields that have meaning, like genus and species).  

I am not familiar with the API beyond what is in the documentation and where the [results of a search for "json" occur in the source code]. It has rarely been used. This was originally implemented by @mulrooney and extended by @gsrohde.

**Comment by sckott** [comment]
@dlebauer It's quite common, in my experience, for APIs to allow retrieval of whatever the thing is they provide by its unique ID. For example, GBIF does this for each species, dataset, and occurrence. All taxonomic of course do this.   But if you don't want to allow it, then that's cool. Up to you. If you want to allow it, a workflow might be where a user searches e.g., for species, then gets ids for the ones they want, then they can pass those ids to a function to get data by ID.
