### ISSUE TITLE
gene seqs from ncbi by txid

### ISSUE THREAD

**Issue by mpnelsen** [ropensci/traits#31]
Hi - I'm wondering if it's possible to modify the ncbi_byname function to query by txid instead of organism name?  In the original ncbi_byname function, I've changed taxa->txid and [Organism]->[Organism:noexp], and re-executed, but it's having trouble finding the make_ids function (and I can't track it down on GitHub).  Is there an easy way to add this capability (search by txid) into this function?  Thanks much for the help. -Matt.

**Comment by sckott** [comment]
thanks for the good question @mpnelsen - wrt `make_ids` first...

`make_ids()` is an internal function in the package. While in R, you can find internal functions using triple colon `:::`, so `traits:::make_ids` should print out the function for you, that gives

```r
function(x) as.numeric(sapply(xpathApply(x, "//IdList//Id"), xmlValue))
<environment: namespace:traits>
```

Weird, tried to search on Github and it doesn't find where the function is defined. Anyway, usually that should work :)

**Comment by mpnelsen** [comment]
thanks very much!  problem solved!

**Comment by sckott** [comment]
now wrt searching by taxonomic id, is this the taxon you were searching for in your example in the script http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=27344

That's a good idea to search by taxonomic id. Maybe we should make a generic S3 function that dispatches on character or numeric ID input for either genbank ID, or taxonomic ID, and could use `taxize` to get IDs, then pass into a function in this package to get seq. data

**Comment by mpnelsen** [comment]
that's the taxon.  and that sounds perfect.  that's exactly how i was trying to do it.  thanks much!

**Comment by sckott** [comment]
So that would be useful to add support for your use case in this package?

**Comment by mpnelsen** [comment]
it would be, but i can do it myself if it would have limited use.

**Comment by sckott** [comment]
cool, i'll take a look and see if it's feasible to add, follow new issue #32
