### ISSUE TITLE
Generalize ncbi_by* to work on taxonomic IDs

### ISSUE THREAD

**Issue by sckott** [ropensci/traits#32]
from #31 

both from character/numeric tax id and from `taxize` id classes

**Comment by sckott** [comment]
hmm, forgot that we have taxid support in `ncdbi_searcher()` - did you see that @mpnelsen ?

**Comment by mpnelsen** [comment]
thanks - yes, i had.  i was initially interested in ncbi_by* b/c it automatically selects the longest sequence (which is what i was after), but i'm just parsing the output from ncbi_searcher and grabbing the longest that way.

**Comment by sckott** [comment]
Okay, i think this should be the plan for ncbi functions:

* Drop the `ncbi_byname()` function - seems like `ncbi_searcher()` does the same stuff, but does more, and taxonomic searching is already supported in `ncbi_searcher()`
* See if `ncbi_byid()` can be used to search by gi number as well, or just accession number

does this plan sound okay @mpnelsen

**Comment by mpnelsen** [comment]
Sounds good.

I think the only advantages of ncbi_byname() over ncbi_searcher() that I
can think of, is that (1) if the user wants the longest sequence for that
search...ncbi_byname() will automatically find it, while ncbi_searcher()
gives you a listing of those retrieved, but the output can then easily be
filtered afterwards when using ncbi_searcher().  And (2) ncbi_byname()
retrieves the actual sequence, too, whereas ncbi_searcher() does not.

Your call (obviousy!) w ncbi_id() - that's a good idea to check GI vs Acc
No.

Thanks again for all your help.

**Comment by sckott** [comment]
Thanks for the feedback. Right, had forgotten that `ncbi_byname()` is meant for retrieving sequences, while `ncbi_searcher()` is meant for searching (but not getting sequences). 

I think we can still retain an option of getting the longest sequence in `ncbi_byid()`, add a parameter to toggle that option.

I think it would simplify to only have `ncbi_searcher()` and `ncbi_byid()`, one fxn to search and one to get sequence data, where `ncbi_byid()` with changes could accept data.frame output from `ncbi_searcher()`, or a list/vector of accession numbers or GI numbers

sound okay?

**Comment by mpnelsen** [comment]
sounds good to me - thanks!

**Comment by sckott** [comment]
:+1:
