### ISSUE TITLE
ncbi_searcher - retrieve only refseqs?

### ISSUE THREAD

**Issue by mpnelsen** [ropensci/traits#35]
Hi again.  Is it possible to use ncbi_searcher to only search for refseqs?  If not, would it be possible to add this functionality (perhaps an if/else statement around lines 130-134 that would add in srcdb_refseq[PROP] to the query)?  Thanks again.

**Comment by sckott** [comment]
Can you not already do that by passing that query in via the `entrez_query` parameter?

**Comment by mpnelsen** [comment]
Sorry - forgot to mention I did actually try that before writing:

> library(traits)
> search.res<-ncbi_searcher(taxa="Pezizales",getrelated=FALSE,entrez_query="internal transcribed spacer AND srcdb_refseq[PROP]",verbose=FALSE,seqrange="350:3500")
> nrow(search.res)
[1] 0

whereas through NCBI I get 38 hits: 

http://www.ncbi.nlm.nih.gov/nuccore/?term=pezizales%5BORGN%5D+AND+internal+transcribed+spacer+AND+srcdb_refseq%5BPROP%5D

I'd also tried looking at rentrez, but I don't think that accesses the refseq db (at least I'm not seeing it when checking available dbs w entrez_dbs).

**Comment by sckott** [comment]
Hmm, that search `pezizales[ORGN]` is different than what happens inside the function. Since we convert any taxonomic name to a NCBI UID first, we get for pezizales 5185 http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=5185 - which then when passed to eutils as the query (from your e.g.) `txid5185 AND 350:3500[SLEN] AND internal transcribed spacer AND srcdb_refseq[PROP]` we get no results. And there's no results for just `txid5185` either. I'm not sure why though.  anyway, point being we can't do `pezizales[ORGN]` in this function. 

wrt the point of this issue, `refseqs`, here's an example that works (I think, you tell me, i'm not super familiar with molecular data)

```r
<r> one <- ncbi_searcher(taxa = "Salmonella enterica", entrez_query="srcdb_refseq[PROP]")
<r> two <- ncbi_searcher(taxa = "Salmonella enterica")
<r> head(one)
#>                 taxon length                                                                                                  gene_desc acc_no
#> 1 Salmonella enterica   2699                                                      Salmonella enterica plasmid pSGI15, complete sequence 012916
#> 2 Salmonella enterica   2706                       Salmonella enterica strain BB1063 plasmid pB1010 transposon Tn1548, partial sequence 041249
#> 3 Salmonella enterica    812 Salmonella enterica plasmid 05-0001Tc1 genotype trbA-pndC-2 TrbA (trbA) and PndC (pndC) genes, partial cds 036574
#> 4 Salmonella enterica   1080            Salmonella enterica plasmid pCN2310 extended-spectrum beta-lactamase TEM-138 gene, complete cds 036036
      gi_no
#> 1 253723602
#> 2 695225278
#> 3 695213216
#> 4 695211221
<r> NROW(one)
#> [1] 4
<r> NROW(two)
#> [1] 500
```

**Comment by mpnelsen** [comment]
Thanks much.  That helps a lot - I misunderstood some things (that it searches for UID when name supplied).  So I think my search listed above failed in traits b/c I need to add fuzzy=TRUE.  If I do that, it's golden (as it is not searching strictly for that UID, but instead is allowing for children of that UID to also be retrieved.

> library(traits)
> search.res<-ncbi_searcher(taxa="Pezizales",getrelated=FALSE,entrez_query="internal transcribed spacer AND srcdb_refseq[PROP]",verbose=FALSE,seqrange="350:3500",fuzzy=TRUE)
> nrow(search.res)
[1] 38

Sorry I overlooked that, and thanks much for your help clarifying this!
