### ISSUE TITLE
EOL traitbase: error when measurements not present

### ISSUE THREAD

**Issue by aammd** [ropensci/traits#37]
Pulling trait data from EOL sometimes works, but I've found at least one problem taxa:

```r
res <- traitbank(846827)
Error in data.frame(df, `dwc:measurementValue` = meas, `dwc:measurementValue.id` = meas_id,  : 
  arguments imply differing number of rows: 19, 0
```
The GET request works fine; the problem seems to occur when the results are being turned into a `data.frame` [here](https://github.com/ropensci/traits/blob/9afa5e9f611b43d528d0b44626db683de31098b4/R/traitbank.R#L35-L36)

**Comment by sckott** [comment]
Woops,  sorry.  Back to computer  on the 6th,  can fix then, but carl etc can merge a PR if you have time

**Comment by sckott** [comment]
@aammd okay, after reinstall, does that work for you? 

I renamed the `trait` param to `pageid` since `trait` indicates that it's an id for a trait, when it really is an id for a species page on EOL - anyway, breaking change, but its the first parameter in the function

**Comment by sckott** [comment]
I'll assume this is fixed

**Comment by aammd** [comment]
It is indeed, as far as I can tell! :sweat_smile:

**Comment by sckott** [comment]
Cool cool
