### ISSUE TITLE
Fxn suffixes standardization

### ISSUE THREAD

**Issue by sckott** [ropensci/traits#39]
Right now, each data source has its own prefix. Suffixes after that prefix vary though. What can be standardized across data sources. I'll make a list here

**Comment by sckott** [comment]
cc @hlapp @xu-hong

**Comment by sckott** [comment]
What follows is some discussion of the current function names:

these were named working with BetyDB folks, and I think they thought these made the most sense

* `betydb_citation` - no analog I can see elsewhere
* `betydb_search` - Most of the other data sources below don't have a search service, so this suffix isn't seen much elsewhere
* `betydb_site` - __this could be joined with coral_locations below__
* `betydb_specie` - __could maybe be combined with coral_taxa, but coral_taxa gives back all records for that taxon, whereas this function gives back just metadata for the species__
* `betydb_trait` - __this could be joined with coral_traits below__

* `birdlife_habitat`/`birdlife_threats` - Birdlife International had two bits of data, one for habitat information, and one for threats,  so it made sense to have two fxns, one for each
* `coral_locations` - Get location information by location ID
* `coral_methodologies` - Get methodology info by method ID
* `coral_resources` - Get resources by resource ID
* `coral_species` - Get list of species
* `coral_taxa` - Get taxa info by taxon ID
* `coral_traits` - Get trait info by trait ID
* `eol_invasive_` - __this and next three could be combined under one suffix, e.g., `nativity` or `origin` or something else?__
* `fe_native` - 
* `g_invasive` - 
* `is_native` - 
* `leda` - only does one thing, get trait data back by _trait name_ (not taxon name or ID), so no suffix, should it have one?
* `ncbi_byid` - 
* `ncbi_byname` - 
* `ncbi_searcher` - has `searcher` instead of `search` to avoid conflict with `taxize`, where these 3 `ncbi` functions were moved from. 
* `traitbank` - only does one thing, get trait data back by EOL page ID, so no suffix, should it have one?

**Comment by sckott** [comment]
Okay, have some suggested fxn name changes above (see those with `fxn_name -> new_fxn_name`)

Let me know if you have any other ideas.

**Comment by hlapp** [comment]
> * eol_invasive_ -> eol_origin (but make synonym for old fxn name too)
> * fe_native -> fe_origin (but make synonym for old fxn name too)
> * g_invasive -> gisd_origin (bring gisd back since that fxn is now defunct in taxize (but make synonym for old fxn name too)

Just to confirm, this means that these functions are not about invasive or native species but about something else (not sure what the `_origin` suffix is meant to signify though)?

**Comment by sckott** [comment]
They vary a bit, but are about whether a species is native or not in a particular region/country/etc. The reason i thought of the word `origin` is I imagine b/c of ITIS, e.g., http://www.itis.gov/ITISWebService/services/ITISService/getJurisdictionalOriginFromTSN?tsn=180543 where they use `origin` to refer to whether a species is native or not

`origin` does seem to colloquially refer to _where_ something is from, not whether it was originally from there or not. 

We could look at Darwin Core - looks like it uses `establishmentMeans` for this type of data   http://rs.tdwg.org/dwc/terms/#establishmentMeans - but to me that isn't really a clear term either

thoughts?
