### ISSUE TITLE
Search by taxonomic name(s)

### ISSUE THREAD

**Issue by sckott** [ropensci/traits#40]
- Input a single name 
- Input many names
- Get data for all taxa hierarchically below a given taxon name - This currently isn't possible R client side, though may be done by individual data sources server side (I don't know though if any do) - I'd suggest we direct people/show examples of using `taxize` to do the name fetching part, then pass that to functions in this pkg to get traits
- Search by taxonomic ID - we have some NBCI fxns here, which we could pass their taxon ID (the `UID`) to get data -  possible in `traits::ncbi_byid()` & `traits::birdlife()` uses the IUCN ID to search https://github.com/ropensci/traits/blob/master/R/birdlife.R

**Comment by sckott** [comment]
cc @hlapp @xu-hong

**Comment by sckott** [comment]
A proposed new function:

```r
taxa_search <- function(x, db, ...) {  
  UseMethod("taxa_search")
}

# method for character input, e.g., "Poa annua", or c(...)
taxa_search.character <- function(x, db, ...) { ... }

# method for list input, e.g., list("Poa annua", "Pinus contorta")
taxa_search.character <- function(x, db, ...) { ... }

# method for data.frame/matrix input, where trait data given back as data.frame, 
# one row for each taxon, ideally
taxa_search.character <- function(x, db, ...) { ... }

# e.g. use
taxa_search("Poa annua", db = c("leda", "traitbank"))
```

**Comment by maelle** [comment]
> traits::birdlife() uses the IUCN ID
Interesting, so my workflow in my upcoming blog post will be scientific name to IUCN ID via `rredlist`/`taxize` to trait data via `traits` (BirdLife). No new function from me, but well it'll be an use case.

**Comment by sckott** [comment]
awesome, thanks @maelle
