### ISSUE TITLE
Error when using traitbank

### ISSUE THREAD

**Issue by cmungall** [ropensci/traits#46]
From the example page:

```
> library("traits")
> res <- traitbank(trait = 328566)
Error in paste0(tburl(), pageid) : 
  argument "pageid" is missing, with no default
```

Same for other IDs

I'm guessing this is an upstream API issue, thought I would check here first

**Comment by sckott** [comment]
hey @cmungall - thanks for the report 

we did a bad thing a while back (wrt breaking the pkg API that is) https://github.com/ropensci/traits/commit/ec8adf9225323d58646c75f889cc8b9fce0ae815#diff-7c2950c2b616ad5d362f1bda908e37c7L20

renamed the `trait` parameter to `pageid`  - I thought `trait` was so misleading as to necessitate the change. That is, the value that EOL wants is a ID for a taxon page (e.g,. the one in your eg. http://eol.org/pages/328566/overview )  - which is indeed not a trait, but a taxon

The only interface they provide to Traitbank is via fetching data for a species as far as I know,

**Comment by cmungall** [comment]
I agree that was a confusing parameter name!

I can confirm that using pageid works, or just the pageid as the sole argument. And I see now the documentation on github is in sync, it's just the rOpenSci version of the docs that are lagging

And you anticipated my next question. It would be awesome to be able to query by traits, or to get bigger chunks of data without iterating over species... I believe they have a triplestore, but don't expose the SPARQL endpoint, so looks like this is all we can do for now

**Comment by sckott** [comment]
Thanks for note, I'll update https://ropensci.org/tutorials/traits_tutorial.html for the changes

Yeah, it's too bad access is so limited :(
