### ISSUE TITLE
What data will rotraits query and return (what is a "proper" API format)?

### ISSUE THREAD

**Issue by dlebauer** [ropensci/traits#5]
in gh-1, the issue says that "response type isn't properly formatted".

What is the proper format?
What data do you want to query?
How do you want to provide it?

I ask (related to gh-3) because we are working on this and want to know how to make our API more useful, and perhaps help contribute to / facilitate this package.

An example of data that we provide for download as csv is [this gist](https://gist.github.com/dlebauer/10442773). You can get the full download by going to [betydb.org](https://betydb.org) -> enter "switchgrass" in search box -> download results. This is different than our API, though it should be possible to construct the same / similar query via the API.

**Comment by sckott** [comment]
closing
