### ISSUE TITLE
EOL Traitbank Error

### ISSUE THREAD

**Issue by Rekyt** [ropensci/traits#57]
When trying to reproduce the example of function `traitbank()` I obtain an error with current development version of `traits`:

```r
library(traits)
traitbank(328574)
#>Error in traitbank_GET(paste0(tburl(), pageid), args, ...) :
#>  server error: (500) Internal Server Error
```

**Comment by sckott** [comment]
EOL servers are not working, e.g.,  w/ http://eol.org/api/traits/846827

```
[
    {
        error: "Sorry, there was a problem"
    }
]
```

**Comment by sckott** [comment]
That is to say, we can't do anything to fix this, though I'll ping them in case they dont' know

**Comment by Rekyt** [comment]
Ah! Thanks ;) I didn't think they had a problem.

**Comment by sckott** [comment]
Seems that their traits API is still not working, sorry about that

**Comment by sckott** [comment]
the traitbank page says

> Sorry, this feature is temporarily disabled. Check back soon.

Uhoh, hopefully it's not down for good

**Comment by rvosa** [comment]
I'm still getting period error 500 messages, for example in a loop. Could it be that we're hitting the server too hard or something?

**Comment by sckott** [comment]
@rvosa I would guess that they can't handle very heavy loads and they are just intermittently throwing 500's when they fail over

**Comment by rvosa** [comment]
What do you think? Should I put a sleep between every iteration or
something?

**Comment by sckott** [comment]
maybe wrap in `tryCatch` and if an error detected, then sleep a bit, then retry

```r
res <- tryCatch(traitbank(x), error = function(e) e)
if (inherits(res, "error")) {
    Sys.sleep(sleep_time)
    res <- tryCatch(traitbank(x), error = function(e) e)
    if (inherits(res, "error")) {
        # put a placeholder for this query and try again later maybe?
    }
}
```

you probably have a setup that's best for your use case, but something like above
