### ISSUE TITLE
ncbi_byid does not return full taxon names

### ISSUE THREAD

**Issue by sborstein** [ropensci/traits#71]
ncbi_byid function does not return full taxon names for undescribed species, cf., aff., or trinomial subspecies. Some example accession numbers are:
AJ845086.1 – returns only the binomial and not the subspecific epithet.
KJ127340.1 – returns up to the cf.
KJ127317.1 – returns taxon name up to sp.

Thanks,
-Sam

**Comment by sckott** [comment]
thanks for the report @sborstein - will have a look

**Comment by sckott** [comment]
sorry for delay, looking at this now. it's an annoying parsing problem because they give back just a string of data which we have to regex

**Comment by sckott** [comment]
the names are so messy with fasta files, and there is taxon info on the page for each acc ID, so thinking of pulling down data differently

**Comment by sckott** [comment]
@sborstein okay, try again after reinstalling like `devtools::install_github("ropensci/traits")` let me know if it works or not

**Comment by sborstein** [comment]
Hi Scott,

 

I just tried it out and it is working! Thanks for your help with this.

 

Thanks,

-Sam Borstein

sam@borstein.com <mailto:sam@borstein.com> 

PhD Candidate

University of Tennessee

Dept. of Ecology and Evo. Bio.

**Comment by sckott** [comment]
great! glad it works
