### ISSUE TITLE
How can I make url an optional parameter in betydb_* functions?

### ISSUE THREAD

**Issue by dlebauer** [ropensci/traits#74]
On line 159 of [R/betydb.R](https://github.com/ropensci/traits/blob/master/R/betydb.R#L159) there is a helper function `betyurl <- function() 'https://www.betydb.org/'`

However, BETYdb is a federated network of databases, betydb.org was the first, and all of the instances sync their public data (so this is a good default) but we need the ability to specify the url.

I'd like to add `url` as an argument to each function call, or perhaps use the `options()` function to set this parameter. What is the best way to do this - e.g. by changing `betyurl` or `bety_GET` or otherwise ... advice appreciated.

@sckott ?

**Comment by sckott** [comment]
Hey @dlebauer - Let's create a new parameter `url` to pass in a url, sound good?

**Comment by dlebauer** [comment]
Thats easy: replace `betyurl()` and pass in url parameter to every function that currently calls it.

Did you originally create the function in order to only specify the actual url once? To set a default, should I keep the `betyurl()` function and add `url = betyurl()` where necessary?

**Comment by dlebauer** [comment]
PS it might not have been clear but I'll do it!

**Comment by sckott** [comment]
> Did you originally create the function in order to only specify the actual url once? 

I didn't know you'd need different urls :)

> To set a default, should I keep the betyurl() function and add url = betyurl() where necessary?

yeah, or just `url = "https://www.betydb.org"`

**Comment by dlebauer** [comment]
OK. The feature is implemented in #75 and this can be closed.
