### ISSUE TITLE
Accept multiple IDs in betydb_*(id=...)?

### ISSUE THREAD

**Issue by infotroph** [ropensci/traits#83]
The `id` argument to all BETY functions is currently documented as (emphasis added) "One **or more** ids for a species, site, variable, etc." But at present no function handles multiple IDs gracefully.

```r
betydb_specie(id=c(937, 222))
# Error: length(url) == 1 is not TRUE
# In addition: Warning message:
# In if (!grepl("/api/", url, fixed = TRUE)) { :
#  the condition has length > 1 and only the first element will be used

betydb_query(id=c(937, 222), genus="Miscanthus", table="species")
# Error in vapply(elements, encode, character(1)) : 
#  values must be length 1,
#  but FUN(X[[2]]) result is length 2
```

* In the "plural" functions (eg `betydb_query`), it *could* make sense to interpret it as an OR operation so that `betydb_query(id=c(1, 937, 222), ...)` := `betydb_query(id="~^(1|937|222)$", ...)`, but maybe that's too magic and the user should construct the regex themselves if they want it. Also not compatible with v0 API.

* In the "singular" functions (eg `betydb_specie`) it only makes sense to send one ID per request, so I see two ~reasonable behaviors:
    - Continue to only support single IDs
    - Fetch all IDs and return them as a list of records: `betydb_specie(c(1, 2, 3), ...)` := `lapply(c(1, 2, 3), FUN=betydb_item, table="species", ...)`

Thoughts, @dlebauer?

**Comment by sckott** [comment]
I guess it's up to you @infotroph and @dlebauer - but agreed that this should be clarified

**Comment by sckott** [comment]
@infotroph @dlebauer  Is this something that should be dealt with soon, like before the next CRAN push? or hold off for a while (that is, should I put it in the milestone for the next CRAN push, or on a later milestone?)

**Comment by dlebauer** [comment]
Hold off, this is lower priority

**Comment by maelle** [comment]
This repository is about to be archived.
