### ISSUE TITLE
`\%>\%` in betydb_query examples

### ISSUE THREAD

**Issue by infotroph** [ropensci/traits#92]
Fix, rerun Roxygen, check other pages for same error.

**Comment by infotroph** [comment]
I think this is an issue with GitHub's Rmarkdown rendering. The percents appear correctly, with no extra backslashes, when viewed in R.

**Comment by sckott** [comment]
all good now?

**Comment by infotroph** [comment]
The tidyverse docs look the same way. So yep, we're all good.
