### ISSUE TITLE
next cran push

### ISSUE THREAD

**Issue by sckott** [ropensci/traits#93]
@infotroph @dlebauer 

i've gone through issues, and next cran push will be this milestone https://github.com/ropensci/traits/milestone/6 

so I have a few things to deal with before going to cran - let me know if there's anything that should or shouldn't be on the milestone wrt BETYdb

**Comment by sckott** [comment]
thoughts @dlebauer @infotroph ^^

**Comment by infotroph** [comment]
I think you found all the BETY changes that are ready to go. The remaining issues I see all need more thought (#83, #84) and/or coordination with a larger package cleanup (#38, #39). 

Of the other issues in this milestone, looks like httr-->crul (#89) is the only one that might require changes in the BETY code. Does crul provide a drop-in replacement for httr::GET?

**Comment by sckott** [comment]
it's easy enough to do the conversion to `crul` - but I think I’ll move it to the next milestone just to speed up this one

**Comment by infotroph** [comment]
May need to revisit #52 -- `include_unchecked` only works in some API versions. We should resolve this before release.

**Comment by dlebauer** [comment]
I think include_unchecked was absent in v0 and new in beta

**Comment by dlebauer** [comment]
Hi @sckott when do you think the next version will be released to CRAN? There are some useful changes that Chris did that would be great to have available in the official version.

**Comment by sckott** [comment]
the next milestone is https://github.com/ropensci/traits/milestone/4 a few of the issues will be very quick, and the others i'll poke at and may move to a future milestone if they will take too long. - so soonish
